perfect_place_user_register:
    path:     /register
    defaults: { _controller: PerfectPlaceUserBundle:Default:register }

perfect_place_user_login:
    path:     /login
    defaults: { _controller: PerfectPlaceUserBundle:Default:login }
