perfect_place_user:
    resource: "@PerfectPlaceUserBundle/Resources/config/routing.yml"
    prefix:   /

perfect_place_core:
    resource: "@PerfectPlaceCoreBundle/Resources/config/routing.yml"
    prefix:   /

