parameters:
#    perfect_place_core.example.class: PerfectPlace\CoreBundle\Example

services:
#    perfect_place_core.example:
#        class: %perfect_place_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
